# practice1

In [77]:
print('hello')

hello


## numpy arrays

In [78]:
import numpy as np

In [79]:
mylist = [1,2,3]

In [80]:
type(mylist)

list

In [81]:
np.array(mylist)

array([1, 2, 3])

In [82]:
mylist

[1, 2, 3]

In [83]:
myarr = np.array(mylist)

In [84]:
myarr

array([1, 2, 3])

In [85]:
type(myarr)

numpy.ndarray

In [86]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [87]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [88]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [89]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [90]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [91]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [92]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [93]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [94]:
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [95]:
len(np.linspace(0,5,21))

21

In [96]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [32]:
np.random.rand(1)

array([0.07918402])

In [97]:
np.random.rand(5,2)

array([[0.96990985, 0.83244264],
       [0.21233911, 0.18182497],
       [0.18340451, 0.30424224],
       [0.52475643, 0.43194502],
       [0.29122914, 0.61185289]])

In [98]:
np.random.randn(2,3)

array([[-0.42804606, -0.74240684, -0.7033438 ],
       [-2.13962066, -0.62947496,  0.59772047]])

In [99]:
np.random.randint(0,101,(4,5))

array([[ 54,  63,   2, 100,  50],
       [  6,  20,  72,  38,  17],
       [  3,  88,  59,  13,   8],
       [ 89,  52,   1,  83,  91]])

In [100]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [101]:
arr = np.arange(0,25)

In [102]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [103]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [104]:
ranarr = np.random.randint(0,101,10)

In [106]:
ranarr

array([82, 86, 74, 74, 87, 99, 23,  2, 21, 52])

In [107]:
ranarr.max()

99

In [108]:
ranarr.min()

2

In [109]:
ranarr.argmax()

5

In [110]:
ranarr.argmin()

7

In [111]:
ranarr.dtype

dtype('int32')

In [112]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [113]:
arr.shape

(25,)

In [114]:
arr = arr.reshape(5,5)

In [115]:
arr.shape

(5, 5)

In [116]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])